version: 1

reviews:
  auto_review: true
  review_status: true
  comment_style: concise

  rules:
    - focus: readability
    - focus: performance
    - focus: security
    - focus: best_practices

  path_filters:
    exclude:
      - node_modules/**
      - .next/**
      - public/**
      - *.lock

comments:
  summary: true
  inline: true

language_support:
  javascript: true
  typescript: true

ai:
  tone: constructive
  explain_reasoning: true
  suggest_improvements: true
